Fixed bug and condition matching on architecture in preinst script (uMurmur)

diff --git a/src/umurmur/scripts/prepost-common b/src/umurmur/scripts/prepost-common
--- a/src/umurmur/scripts/prepost-common
+++ b/src/umurmur/scripts/prepost-common
@@ -24,12 +24,9 @@ arch=`echo $synoinfo | cut -d_ -f2`
 preinst ()
 {
 	# Check if the architecture is supported
-	if [ "$arch" != "%SPK_ARCH%" ]; then
-		echo "Your architecture is not supported by this package, sorry."
-		echo "Architecture  : $arch"
-		echo "Synology info : $synoinfo"
+	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
+		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
 		exit 1
-		;;
 	fi
 	exit 0
 }
